services:
  - type: web
    name: student-progess-track-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: student-progess-track-db
          property: connectionString

databases:
  - name: student-progess-track-db
    databaseName: student-progess-track